// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/legacy/ReactDOMRe.bs.js");
var Nonsense$Nonsense = require("./Nonsense.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Nonsense$Nonsense.make, {}), "nonsense");

/*  Not a pure module */
